- name: Download wordpress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract wordpress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/wordpress/.
    dest: /var/www/html
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: app/templates/wp-config.php.j2
    dest: /var/www/html/wp-config.php

- name: Restart service apache
  ansible.builtin.service:
    name: apache2
    state: restarted